// <auto-generated />
using System;
using Casor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Casor.Infrastructure.Migrations
{
    [DbContext(typeof(CasorDbContext))]
    partial class CasorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Casor.Domain.Entidades.AjusteInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comprobante")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ajuste_inventario", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Datos")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.CajaSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CierreX")
                        .HasColumnType("boolean");

                    b.Property<bool>("CierreZ")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoApertura")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal?>("MontoCierreDeclarado")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal?>("MontoCierreSistema")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("caja_sesion", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Giro")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefonico")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text");

                    b.Property<string>("RutCliente")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("RutCliente")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.DetalleAjuste", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AjusteId")
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadContada")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadSistema")
                        .HasColumnType("integer");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AjusteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalle_ajuste", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.DetalleVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PromocionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("PromocionId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalle_venta", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DireccionMatriz")
                        .HasColumnType("text");

                    b.Property<string>("Giro")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.FolioCaf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<long>("RangoDesde")
                        .HasColumnType("bigint");

                    b.Property<long>("RangoHasta")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long?>("UltimoFolioUsado")
                        .HasColumnType("bigint");

                    b.Property<string>("XmlCaf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("folio_caf", null, t =>
                        {
                            t.HasCheckConstraint("ck_caf_rango", "\"RangoHasta\" >= \"RangoDesde\"");
                        });
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.PrecioHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("VigenteDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VigenteHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProductoId", "VigenteDesde");

                    b.ToTable("precio_historico", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.PrincipioActivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("principio_activo", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadPresentacion")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Concentracion")
                        .HasColumnType("text");

                    b.Property<string>("CondicionVenta")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal?>("CostoUnitario")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Linea")
                        .HasColumnType("text");

                    b.Property<string>("NombreIsp")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid?>("PresentacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrincipioActivoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Refrigerado")
                        .HasColumnType("boolean");

                    b.Property<int>("StockMaximo")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("TitularIsp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarra")
                        .IsUnique();

                    b.HasIndex("Descripcion");

                    b.HasIndex("PresentacionId");

                    b.HasIndex("PrincipioActivoId");

                    b.ToTable("producto", null, t =>
                        {
                            t.HasCheckConstraint("ck_producto_precio", "\"PrecioVenta\" >= 0");

                            t.HasCheckConstraint("ck_producto_stockmin", "\"StockMinimo\" >= 0");
                        });
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Promocion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("promocion", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.RecetaRetenida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalleVentaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<long>("FolioLibro")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerieRecetaCheque")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DetalleVentaId")
                        .IsUnique();

                    b.HasIndex("Tipo", "FolioLibro")
                        .IsUnique();

                    b.ToTable("receta_retenida", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.StockSucursal", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FechaVencimientoProxima")
                        .HasColumnType("date");

                    b.HasKey("ProductoId", "SucursalId");

                    b.HasIndex("SucursalId");

                    b.ToTable("stock_sucursal", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_no_negativo", "\"CantidadActual\" >= 0");
                        });
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("sucursal", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.TipoPresentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NombreMedida")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("NombreMedida")
                        .IsUnique();

                    b.ToTable("tipo_presentacion", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Rut")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CajaSesionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EmitidaOffline")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoDte")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoVenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("FechaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Folio")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalBruto")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("TotalNeto")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VentaOrigenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CajaSesionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaVenta");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaOrigenId");

                    b.HasIndex("TipoDocumento", "Folio")
                        .IsUnique()
                        .HasFilter("\"Folio\" IS NOT NULL");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("Casor.Domain.Entidades.AjusteInventario", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Auditoria", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.CajaSesion", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.DetalleAjuste", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.AjusteInventario", "Ajuste")
                        .WithMany("Detalles")
                        .HasForeignKey("AjusteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ajuste");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.DetalleVenta", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Promocion", "Promocion")
                        .WithMany()
                        .HasForeignKey("PromocionId");

                    b.HasOne("Casor.Domain.Entidades.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Promocion");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.FolioCaf", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.Navigation("Empresa");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Pago", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.PrecioHistorico", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Producto", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.TipoPresentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("PresentacionId");

                    b.HasOne("Casor.Domain.Entidades.PrincipioActivo", "PrincipioActivo")
                        .WithMany()
                        .HasForeignKey("PrincipioActivoId");

                    b.Navigation("Presentacion");

                    b.Navigation("PrincipioActivo");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.RecetaRetenida", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.DetalleVenta", "DetalleVenta")
                        .WithMany()
                        .HasForeignKey("DetalleVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.StockSucursal", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Sucursal", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Venta", b =>
                {
                    b.HasOne("Casor.Domain.Entidades.CajaSesion", "CajaSesion")
                        .WithMany()
                        .HasForeignKey("CajaSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Casor.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Casor.Domain.Entidades.Venta", "VentaOrigen")
                        .WithMany()
                        .HasForeignKey("VentaOrigenId");

                    b.Navigation("CajaSesion");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");

                    b.Navigation("VentaOrigen");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.AjusteInventario", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Empresa", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Casor.Domain.Entidades.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
